# noinspection SpellCheckingInspection
trans_code = {'A/D': 'AirDog PureFlow',
              'A/I': 'Artec Industries',
              'A/P': 'ALL PRO OFF ROAD',
              'AAC': 'Advanced Accessory Concepts',
              'AAS': 'Power Tank',
              'ACI': 'Access Cover',
              'ACL': 'ACCEL',
              'ACO': 'ADDCO',
              'ACT': 'Action Accessories',
              'ADD': 'Genuine Packages',
              'ADS': 'Addictive Desert Designs',
              'ADV': 'Advance Adapters',
              'AEE': 'ACE Engineering',
              'AEM': 'AEM',
              'AFE': 'Afe Power',
              'AFW': 'American Force Wheels',
              'AGR': 'AGR',
              'AIR': 'AirLift',
              'ALP': 'Alpine',
              'ALS': 'Als Liner',
              'ALY': 'Alloy USA',
              'AMG': 'Auto Meter',
              'AMP': 'AMP-Research',
              'ANT': 'Antenna X',
              'ANZ': 'Anzo',
              'AOC': 'AO Coolers',
              'AOL': 'American Outlaw',
              'APR': 'Advanced Power Systems',
              'AR': 'American Racing Wheels',
              'ARB': 'ARB 4x4 Accessories',
              'ARE': 'American Racing',
              'ARM': 'Armadillo Industries',
              'ARP': 'ARP',
              'ARS': 'Aries Offroad',
              'ART': 'Artec Industries',
              'ASI': 'Assault Industries',
              'ASM': 'AMI',
              'ATA': 'Advantage Truck Accessories',
              'ATC': 'Auto Custom Carpet',
              'ATK': 'ATK NORTH AMERICA',
              'AUB': 'Auburn Gear',
              'AVS': 'Auto Ventshade',
              'AX': 'ATX Wheels',
              'AXI': 'Axia Alloys',
              'B/A': 'Body Armor 4x4',
              'B/D': 'Bully Dog',
              'B/M': 'B&M',
              'B/S': 'Bed Slide',
              'B/W': 'Bushwacker',
              'BAJ': 'Baja Designs',
              'BBK': 'BBK Performance',
              'BBS': 'Baer Brakes',
              'BDD': 'Bd Diesel',
              'BEC': 'Be Cool',
              'BED': 'BedRug',
              'BFG': 'BF Goodrich Tires',
              'BII': 'Beams Industries Inc',
              'BIL': 'Bilstein',
              'BKI': 'BAK Industries',
              'BMF': 'BMF Wheel',
              'BNW': 'B&W Hitch',
              'BOR': 'Borla',
              'BPG': 'Berkley Publishing Group',
              'BPS': 'Bulletproof Suspension',
              'BRA': 'Brandmotion',
              'BRK': 'Bracketron Inc.',
              'BRS': 'FlowKooler',
              'BRW': 'Black Rock Wheels',
              'BST': 'Bestop',
              'BTC': 'Berg Toys',
              'BTF': 'Blue Torch Fabworks',
              'BUB': 'Bubba Rope',
              'BUC': 'Borgeson Steering',
              'BUG': 'Buggy Whip',
              'BUL': 'Bullring',
              'Bll': "Beam's Industries Inc.",
              'C/B': 'Centramatic Balancers',
              'C/K': 'Coverking',
              'C/W': 'Carriage Works',
              'C/Z': 'Condition Zero',
              'CAG': 'CageWrx',
              'CAR': 'Carr',
              'CBR': 'Collins Brother',
              'CBU': 'Corbeau',
              'CEN': 'Centerforce',
              'CIP': 'Cipa Mirrors',
              'CLF': 'Cliffride',
              'CLO': 'Clover Patch',
              'CLT': 'Classic Tube',
              'COB': 'Cobra',
              'COG': 'Cognito Motorsports',
              'COR': 'Corsa Performance Exhaust',
              'COV': 'Covercraft',
              'CRE': 'Cremco',
              'CRO': 'Crown Automotive',
              'CRT': 'Curt Manufacturing',
              'CST': 'California Super Trucks',
              'CTM': 'CTM Racing',
              'CTP': 'Trasharoo',
              'CUR': 'Currie',
              'D/C': 'Dick Cepek',
              'D/D': 'DirtyDog 4x4',
              'D/I': 'Prothane',
              'D/K': 'Dashking',
              'D/S': 'Dana Spicer',
              'D/T': 'Doug Thorley Hedders',
              'DAY': 'Daystar',
              'DBZ': 'Dirtbagz',
              'DDS': 'Davis Distribution System',
              'DEE': 'Dee-Zee',
              'DEI': 'Design Engineering Inc',
              'DEK': 'Decked Bed Organizer',
              'DER': 'Derale Cooling Accessories',
              'DET': 'Detroit Locker',
              'DIA': 'Diablosport',
              'DOR': 'Dorman',
              'DPC': 'Dynatrac',
              'DRA': 'DrawTite',
              'DRK': 'Drake',
              'DTM': 'Fastway Trailer Products',
              'DUH': 'DU-HA',
              'DUI': 'Davis Unified Ignition',
              'DYN': 'Dynomax Exhaust',
              'E3S': 'E3 Spark Plugs',
              'EAT': 'Eaton',
              'EBC': 'EBC Brakes',
              'ECL': 'Electric Life',
              'EDE': 'Edelbrock',
              'EDG': 'Edge',
              'EFX': 'EFX Tires',
              'EGR': 'EGR',
              'EKL': 'Eklips',
              'EKM': 'EK Motorsports',
              'EMP': 'Empi Inc.',
              'ENE': 'Energy Suspension',
              'EOR': 'End Of The Road',
              'EQU': 'Equus Products Inc.',
              'EVE': 'AIRAID',
              'EXC': 'Excalibur Wheel Accessories',
              'EXP': 'Pro Comp Suspension',
              'F55': 'Factor 55',
              'FAB': 'Fabtech',
              'FFI': 'Fab Fours',
              'FHE': '5 Hour Energy',
              'FIR': 'Firestone Ride-Rite',
              'FLM': 'Flaming River',
              'FLW': 'Flowmaster Exhaust',
              'FLX': 'Flex-A-Lite',
              'FOX': 'Fox Racing Shox',
              'FRC': 'Fierce Tires',
              'FS': 'Firestik',
              'FST': 'Fast Fuel Systems',
              'FUT': 'Factory UTV',
              'G/2': 'G2 Axle and Gear',
              'G/F': 'Ground Force',
              'G/R': 'GenRight',
              'G/W': 'Gorilla Whips',
              'G/Z': 'Goal Zero',
              'GAY': "Gaylord's Truck Lids",
              'GBC': 'GBC Motor Sports',
              'GBE': 'Banks Power',
              'GDR': 'Goodridge',
              'GDY': 'Goodyear Tires',
              'GEN': 'General Tire',
              'GLO': 'Globe Specialty Co.',
              'GME': 'Moser Engineering',
              'GOP': 'GoPro',
              'GOR': 'Gorilla Automotive',
              'GRA': 'Grant Steering Wheels',
              'GRV': 'Garvin Industries',
              'GTP': 'Griffin Thermal Products',
              'GTS': 'GTS',
              'H/H': 'Hidden Hitch',
              'H/L': 'Hi-Lift Jack',
              'H3R': 'H3R Performance',
              'HAN': 'Hanlon Industries',
              'HAW': 'Hawk Performance',
              'HAY': 'Haynes',
              'HCR': 'HCR Racing',
              'HCT': 'Heater Craft',
              'HE': 'Helo',
              'HED': 'Hedman',
              'HEL': 'Hellwig',
              'HES': 'Hesco',
              'HLA': 'Hella',
              'HLP': 'Highlifter',
              'HOL': 'Holley Performance',
              'HOP': 'Hopkins Towing Solutions',
              'HOT': 'Hotchkis Sport Suspension',
              'HOW': 'Howell',
              'HTD': 'MHT Fuel Offroad Wheels',
              'HUS': 'Husky Liners',
              'HUT': 'Hutchinson Wheels',
              'HYL': 'Hyline Offroad',
              'HYP': 'Hypertech',
              'HYS': 'Hays',
              'I/E': 'Insane Jeep Audio',
              'ICO': 'Icon Suspension',
              'IMP': 'Impact Video',
              'INL': 'Inline Tube',
              'INP': 'In Pro Carwear',
              'ISB': 'INSYNC Business Solutions',
              'ITC': 'Interco Birddog',
              'ITP': 'ITP',
              'J/W': 'JW Speaker',
              'JAM': 'Jammock',
              'JBA': 'JBA Headers',
              'JBB': 'Jeep Backbone',
              'JCR': 'JcrOffroad',
              'JEP': 'Jeep',
              'JER': 'J.E. Reel',
              'JET': 'Jet Performance Products',
              'JRP': 'Joes Racing Products',
              'JTK': 'Jeep Tweaks',
              'K/A': 'Kleinn Train Horns',
              'K/C': 'KC HiLites',
              'K/N': 'K&N Filter',
              'KAR': 'Kargo Master',
              'KEE': 'Keeper Corporation',
              'KEN': 'Kentrol',
              'KM': 'KMC Wheels',
              'KNA': 'Kenda Tires',
              'KOH': 'King of the Hammers',
              'KOL': 'Kolpin Powersports',
              'KPA': 'Key Parts',
              'KST': 'King Shocks',
              'KWJ': 'Know Where 2 Jeep',
              'L/F': 'Lightforce',
              'L/G': 'Litegrip LLC',
              'L/S': 'Lowery Supply',
              'LAN': 'Lange Originals',
              'LII': 'Lund',
              'LRG': 'Lrg Rims',
              'LUC': 'Lucas Oil',
              'LUL': 'Lube Locker',
              'M/A': 'Mishimoto',
              'M/F': 'MagnaFlow Exhaust',
              'M/T': 'Mickey Thompson',
              'MAG': 'Mag-Hytec',
              'MAS': 'MasterTop',
              'MAV': 'MavCoat',
              'MAX': 'Max Axe',
              'MBA': 'MBA Inc',
              'MBI': 'Motobook International',
              'MBL': 'Max-Bilt',
              'MBR': 'MBRP',
              'MCE': 'MCE Fenders',
              'MCS': 'MasterCraft Safety',
              'MDR': 'Macdivitt Rubber Co.',
              'MDW': 'Midwest Can Company',
              'MEC': 'MONSTER ENERGY COMPANY',
              'MEL': 'Melling Automotive',
              'MES': 'Magnuson',
              'MGI': 'Mean Green',
              'MHI': 'Monster Hooks',
              'MHT': 'MHT Wheels',
              'MIC': 'Michelin Tires',
              'MID': 'Motive Gear',
              'MIL': 'Mile Marker',
              'MLC': 'Master Lock Company',
              'MLR': 'Mallory Ignition',
              'MMS': 'MOTOR MASTERS',
              'MO': 'Moto Metal',
              'MOB': 'Mob Armor',
              'MOG': 'Moog',
              'MOP': 'Mopar Performance',
              'MPL': 'Master Pull Rope',
              'MPR': 'Motive Products',
              'MRE': 'Mountain Off Road Enterprises',
              'MRG': 'Mr. Gasket Company',
              'MRW': 'Method Race Wheels',
              'MSC': 'Misch 4x4',
              'MSD': 'MSD',
              'MTC': 'MTX Audio',
              'MTS': 'MTS Company',
              'MWH': 'Metal Works Of High Point',
              'MWP': 'Metal & Wire Products',
              'MXX': 'Maxxis Tires',
              'N/F': 'Nfab',
              'NAP': 'Napier Enterprises',
              'NCM': 'New Century Manufacturing',
              'NIF': 'Nifty',
              'NIT': 'Nitto',
              'NOD': 'Nodoors Inc.',
              'NOR': 'Northern',
              'NOV': 'Novus Inc.',
              'NRP': 'Nelson Racing Products',
              'NRT': 'New Ray Toys',
              'OAI': 'Omix-Ada',
              'OCF': 'Off Camber Fabrications',
              'ODY': 'Odyssey Batteries',
              'OLY': 'Olympic 4x4 Products',
              'OMC': 'OMC Offroad',
              'OPI': 'Optronics',
              'OPT': 'Optima Batteries',
              'ORC': 'Oracle Lighting',
              'ORP': 'Go Rhino',
              'ORU': 'Off Road Unlimited',
              'OTB': 'Old Toledo Brands',
              'OXL': 'Ox Locker',
              'P/A': 'Pro Armor',
              'P/D': 'Performance Distributors',
              'PAV': 'Pavement Ends',
              'PCT': 'Pro Comp Tires',
              'PCW': 'Pro Comp Steel Wheels',
              'PEC': 'Pace Edwards',
              'PER': 'Performance Accessories',
              'PIA': 'Piaa Lighting',
              'POD': 'SPOD',
              'POI': 'Point Spring And Drive Shaft Co.',
              'POP': 'POP N lock',
              'POR': 'POR-15',
              'POW': 'Powermaster',
              'PPI': 'Pittman Outdoors',
              'PPW': 'Premier Power Welder',
              'PRL': 'Prestolite',
              'PRP': 'PRP',
              'PRR': 'PCI Race Radios',
              'PRS': 'Pro Series',
              'PSC': 'Poison Spyder Customs',
              'PSK': 'PSK Ltd.',
              'PSL': 'Power Slot',
              'PSM': 'PSC Steering',
              'PSP': 'Pace Setter Performance',
              'PST': 'Power Stop',
              'PTX': 'Power Trax',
              'PUT': 'Putco',
              'PWB': 'Powerbass',
              'PWP': 'Painless Wiring',
              'PXA': 'Pro Comp Alloy Wheels',
              'PYL': 'Pylon',
              'Pll': 'Prime Industries Inc.',
              'QCC': 'Quality Craft Corp.',
              'QKL': 'Quick Light',
              'R/A': 'Road Armor',
              'R/E': 'Rubicon Express',
              'R/G': 'Rightline Gear',
              'R/H': 'Ranch Hand',
              'R/K': 'RK Sport',
              'R/M': 'RIPP Superchargers',
              'R/P': 'R&P 4WD Parts',
              'R/R': 'Hauk Offroad',
              'R/T': 'Rally Tops',
              'R42': 'Rescue 42 Inc.',
              'RAD': 'Radar Tires',
              'RAN': 'Rancho',
              'RAT': 'Random Technology',
              'RBA': 'Dorman Products',
              'RBI': 'Robert Bentley Inc.',
              'RCV': 'RCV Axles',
              'REC': 'Recon',
              'RES': 'Reese',
              'RET': 'Retrax',
              'REV': 'Revtek',
              'RFP': 'Rock Hard 4x4 Parts',
              'RGW': 'Team Gordon',
              'RIC': 'Richmond Gear',
              'RID': 'Riddler Manufacturing',
              'RIG': 'Rigid Industries',
              'RKS': 'Rock Krawler',
              'RNL': 'Roll N Lock',
              'ROC': 'Rocknob LLC',
              'ROL': 'ROLA',
              'ROT': 'RotoPAX',
              'RPK': 'RacePak',
              'RPP': 'Rampage',
              'RSC': 'Oro-Tek',
              'RSE': 'Rock Slide Engineering',
              'RTM': 'Rock Tamers Mud flaps',
              'RTO': 'RT Off-Road',
              'RUG': 'Rugged Ridge',
              'RUS': 'Russell Performance',
              'S/B': 'Smittybilt',
              'S/I': 'Spectra Premium Ind.',
              'S/L': 'Spyder Auto Group',
              'S/P': 'Specialty Products Co.',
              'S/S': 'Street Scene',
              'SAN': 'Sand Tires Unlimited',
              'SAV': 'Savior Products',
              'SAW': 'Sway-A-Way Performance',
              'SCC': 'SCC Security Chain',
              'SCI': 'Superchips',
              'SCT': 'SCT programmers',
              'SD': 'Shocking Deals',
              'SDR': 'SDR Motorsports',
              'SEA': 'Seal Savers',
              'SEI': 'Select Increments',
              'SFK': 'Skid Row Off Road',
              'SKO': 'Sidekick Offroad',
              'SKY': 'Skyjacker',
              'SNB': 'S&B Filters',
              'SOL': 'Scorpion Off Road LLC',
              'SOR': 'SOTA Offroad',
              'SPI': 'Spidertrax Offroad',
              'SPR': 'Supersprings',
              'SRP': 'Simpson Racing',
              'SSB': 'Stainless Steel Brakes',
              'SSC': 'BOLT Lock',
              'SST': 'Super Swamper Tires',
              'SSV': 'SSV Works',
              'SSW': 'Evolution of Off-Road Apparel',
              'ST8': 'Stage 8 Locking Fasteners',
              'STN': 'Coyote Enterprises',
              'STR': 'Star Fabrications',
              'STW': 'STI ATV Wheels',
              'SUN': 'Sun Company',
              'SUR': 'Surco Products',
              'SWI': 'Superwinch',
              'SWS': 'SPIDERWEBSHADE',
              'SYN': 'Synergy Manufacturing',
              'T/C': 'Tuff Country',
              'T/D': 'Trans-Dapt',
              'T/G': 'Tire Gate',
              'T/K': 'Throttle Down Kustoms',
              'T/M': 'Trail Master',
              'T/P': 'Tonno Pro',
              'T/R': 'T-Rex Grilles',
              'T/T': 'TnT Customs',
              'T/W': 'Trail Wax',
              'TAG': 'Tag Accessory Group',
              'TE': 'Tensor Tires',
              'TER': 'TeraFlex',
              'TFI': 'Transfer Flow Inc.',
              'TFP': 'TFP Motoring Accessories',
              'TFY': 'Tuffy',
              'TGI': 'Trail Gear',
              'THU': 'Thule',
              'TIM': 'Timken',
              'TKN': 'Tekonsha',
              'TL': 'Truck-Lite',
              'TLP': 'Traxxas',
              'TMD': 'Truck Master Designs',
              'TOM': 'Tomken Machine',
              'TOW': 'Tow Ready',
              'TOY': 'Toyo Tires',
              'TRC': 'Trico',
              'TRI': 'Trimax Locks',
              'TRK': 'Bartact',
              'TRX': 'TruXedo',
              'TSF': 'Life Is Good',
              'TSI': 'Totally Stainless Inc.',
              'TTN': 'Titan Tanks',
              'TUS': 'Tough Stuff',
              'UIW': 'United Ignition Wire Corp',
              'UND': 'Undercover Tonneau Covers',
              'UNI': 'Unichip',
              'UNV': 'Universal Manufacturing Co.',
              'USS': 'US Speedo',
              'V/A': 'VIAIR',
              'V/X': 'Vision X Lighting',
              'VCC': 'Valco Cincinnati',
              'VDP': 'Vertically Driven Products',
              'VID': 'Videos',
              'VOL': 'Volant',
              'VOO': 'VooDoo Offroad',
              'W/D': 'Welcome Distributing',
              'W/G': 'Weather Guard',
              'W/I': 'Warrior',
              'W/P': 'Wheels Pros',
              'W/S': 'Weigh Safe Hitches',
              'WAR': 'Warn',
              'WAV': 'Wavian',
              'WEA': 'WeatherTech',
              'WEB': 'Weber Carbs',
              'WES': 'Westin',
              'WNP': 'Wrangler NW Power',
              'WOR': 'Wilco Offroad',
              'XD': 'XD Wheels',
              'XEN': 'Xenon',
              'XTC': 'XTC Power Products',
              'XTG': 'Extang',
              'Y/C': 'Yeti Coolers',
              'ZIL': 'Zilla Strap'}
